FROM python:3.11-slim

WORKDIR /app

# Copia el requirements.txt desde la carpeta grupo_1/sistema
COPY ../grupo_1/sistema/requirements.txt .

RUN pip install -r requirements.txt

# Copia todo el código de Flask desde grupo_1/sistema
COPY ../grupo_1/sistema/ .

EXPOSE 5000

CMD ["python", "app.py"]

