version: '3.9'

services:
  gateway:
    container_name: gateway_service
    build:
      context: ../grupo_1/Gateway
      dockerfile: ../../proyecto-software-ii/Dockerfile_gateway
    ports:
      - "8000:8000"
    volumes:
      - ../grupo_1/Gateway:/var/www/html
    networks:
      microservices_network:
        ipv4_address: 172.28.0.2
    depends_on:
      - mysql

  notificaciones:
    container_name: notificaciones_service
    build:
      context: ../grupo_1/notificaciones
      dockerfile: ../../proyecto-software-ii/Dockerfile_gateway
    ports:
      - "8001:8001"
    volumes:
      - ../grupo_1/notificaciones:/var/www/html
    networks:
      microservices_network:
        ipv4_address: 172.28.0.3
    depends_on:
      - mysql

  sistema:
    container_name: sistema_service
    build:
      context: ../grupo_1/sistema
      dockerfile: ../../proyecto-software-ii/Dockerfile_flask
    ports:
      - "5000:5000"
    volumes:
      - ../grupo_1/sistema:/app
    networks:
      microservices_network:
        ipv4_address: 172.28.0.4
    command: python app.py
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development

  mysql:
    container_name: mysql_serviceneutro
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyecto
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      microservices_network:
        ipv4_address: 172.28.0.5

networks:
  microservices_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  mysql_data:
